// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:f6b66b24-432e-4ab3-a21a-3d1834a4a90b",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ChfXeiYSy",
    "aws_user_pools_web_client_id": "1es13umkft757nikk5m0outb0m",
    "oauth": {}
};


export default awsmobile;
