// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:d62cc6f6-6d0c-4dfe-a61b-95a4731a2631",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_dg3nKvSlh",
    "aws_user_pools_web_client_id": "5ebe1fj4c22da9hkb8aac6ne2e",
    "oauth": {},
    "aws_user_files_s3_bucket": "cp-dev08c815b6f3ca4c47a72f5018de38d419devtwo-devtwo",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_mobile_analytics_app_id": "25a4a52b2a934b36be874c32f04d13e8",
    "aws_mobile_analytics_app_region": "eu-west-1"
};
export default awsmobile;
