export const text_fields = 
{
  'passport_info': {'key': 0, 'label': 'PROFILE INFO', 'data_fields': {
    'aliases' : {'key': 0, 'label': 'ALIASES / AKA', 'type': 'typing_bubble'},
    'biography' : {'key': 1, 'label': 'BIOGRAPHY', 'type': 'long_text'},
    'sounds_like' : {'key': 2, 'label': ' SOUNDS LIKE', 'type': 'typing_bubble'},
    'genres' : {'key': 3, 'label': 'GENRES', 'type': 'multiple_bubble_list'},
    'music_roles' : {'key': 4, 'label': 'MUSIC ROLES', 'type': 'multiple_bubble_list'},
    'non_music_roles' : {'key': 5, 'label': 'NON-MUSIC ROLES', 'type': 'typing_bubble'}, 
    'other_skills' : {'key': 6, 'label': ' OTHER SKILLS', 'type': 'typing_bubble'},
    'instruments_played' : {'key': 7, 'label': 'INSTRUMENTS PLAYED', 'type': 'multiple_bubble_list'}, 
    'hardware_used': {'key': 8, 'label': 'HARDWARE USED', 'type': 'typing_bubble'},
    'software_used': {'key': 9, 'label': 'SOFTWARE USED' , 'type': 'typing_bubble'},
    'endorsement': {'key': 10, 'label': 'ENDORSEMENT', 'type': 'long_text'}, //TO CHANGE LATER TO multiple_single_entry_points
    'interests_inspiration': {'key': 11, 'label': 'INTERESTS / INSPIRATION', 'type': 'typing_bubble'},
    'current_projects': {'key': 12, 'label': 'CURRENT PROJECTS', 'type': 'long_text'}, //TO CHANGE LATER TO multiple_single_entry_points
    'favourite_music_makers': {'key': 13, 'label': 'FAVOURITE MUSIC MAKERS', 'type': 'typing_bubble'},
    'charities_supported': {'key': 14, 'label': 'CHARITIES SUPPORTED', 'type': 'typing_bubble'},
    'favourite_quote': {'key': 15, 'label': 'FAVOURITE QUOTE', 'type': 'long_text'}
    },
  },
  'ids': {'key': 1, 'label': 'IDs', 'data_fields': {
      'isni' : {'key': 0, 'label': 'ISNI', 'type': 'single_text'},
      'ipn' : {'key': 1, 'label': 'IPN', 'type': 'single_text'},
      'ipi' : {'key': 2, 'label': 'IPI', 'type': 'single_text'},
      'cp_id': {'key': 3, 'label': 'CP ID', 'type': 'single_text'},
      'other_proprietary_id': {'key': 4, 'label': 'OTHER PROPRIETARY ID', 'type': 'single_text'},
      'system' : {'key': 5, 'label': 'SYSTEM', 'type': 'single_text'},
      'id_number' : {'key': 6, 'label': 'ID NUMBER', 'type': 'single_text'}
    }
  },
  'representatives_contacts': {'key': 2, 'label': 'REPRESENTATIVES AND CONTACTS', 'data_fields': {
      'list_of_representatives': {'key': 0, 'label': 'Representatives', 'type': 'unique_list', 
      'list_items': ['label', 'publisher', 'collection_society', 'distributor', 'pr_agency', 'agent', 'legal', 'Sync AGENCY', 'management', 'general_contact']}}
  },
  'official_links': {'key': 3, 'label': 'OFFICIAL LINKS', 'data_fields': {
    'website' : {'key': 0, 'label': 'WEBSITE', 'type': 'single_text'},
    'merch' : {'key': 1, 'label': 'MERCH', 'type': 'single_text'},
    'facebook' : {'key': 2, 'label': 'FACEBOOK', 'type': 'single_text'},
    'instagram' : {'key': 3, 'label': 'TWITTER', 'type': 'single_text'},
    'tiktok' : {'key': 4, 'label': 'TIKTOK', 'type': 'single_text'},
    'snapchat' : {'key': 5, 'label': 'SNAPCHAT', 'type': 'single_text'},
    'youtube' : {'key': 6, 'label': 'YOUTUBE', 'type': 'single_text'},
    'spotify' : {'key': 7, 'label': 'SPOTIFY', 'type': 'single_text'},
    'apple_music' : {'key': 8, 'label': 'APPLE MUSIC', 'type': 'single_text'},
    'vevo' : {'key': 9, 'label': 'VEVO', 'type': 'single_text'},
    'twitch' : {'key': 10, 'label': 'TWITCH', 'type': 'single_text'},
    'bandcamp' : {'key': 11, 'label': 'BANDCAMP', 'type': 'single_text'},
    'songkick' : {'key': 12, 'label': 'SONGKICK', 'type': 'single_text'},
    'deezer' : {'key': 13, 'label': 'DEEZER', 'type': 'single_text'},
    'imvdb' : {'key': 14, 'label': 'IMVDB', 'type': 'single_text'},
    'genius' : {'key': 15, 'label': 'GENIUS', 'type': 'single_text'}
    }
  },
  'external_data': {'key': 4, 'label': 'EXTERNAL DATA', 'data_fields': {}
  },
  'music_services': {'key': 5, 'label': 'MUSIC SERVICES', 'data_fields': {}
  },
  'credits': {'key': 6, 'label': 'CREDITS', 'data_fields': {}
  },
  'performances': {'key': 7, 'label': 'PERFORMANCES', 'data_fields': {}
  },
  'other': {'key': 8, 'label': 'OTHER', 'data_fields': {}
  }
}

export const representatives = {
  // 'label': {'key': 0, 'label': 'LABELS', 'type': 'typing_bubble', 'additional_info': {
      // 'name': {'key': 0, 'label': 'EMAIL', 'type': 'typing_bubble'},
      //   'email_address' : {'key': 0, 'label': 'EMAIL', 'type': 'single_text'},
      //   'contact_person' : {'key': 1, 'label': 'Contact Person', 'type': 'single_text'},
      //   'additional_info' : {'key': 2, 'label': 'Addiitional Info', 'type': 'single_text'}
      // }},
      // 'publisher': {'key': 1, 'label': 'PUBLISHER', 'type': 'unique_list', 'additional_info': {
      //   'email_address' : {'key': 0, 'label': 'PUBLISHER', 'type': 'single_text'},
      //   'contact_person' : {'key': 1, 'label': 'PUBLISHER', 'type': 'single_text'},
      //   'additional_info' : {'key': 2, 'label': 'PUBLISHER', 'type': 'single_text'}
      // }},
      // 'collection_societies': {'key': 2, 'label': 'COLLECTION SOCIETIES', 'type': 'typing_bubble'},
      // 'distributors': {'key': 3, 'label': 'DISTRIBUTORS', 'type': 'typing_bubble'},
      // 'pr_agency': {'key': 11, 'label': 'PR AGENCY', 'type': 'unique_list', 'additional_info': {
      //     'email_address' : {'key': 0, 'label': 'PR AGENCY', 'type': 'single_text'},
      //     'contact_person' : {'key': 1, 'label': 'PR AGENCY', 'type': 'single_text'},
      //     'additional_info' : {'key': 2, 'label': 'PR AGENCY', 'type': 'single_text'},
      // }},
      // 'agent': {'key': 4, 'label': 'AGENT', 'type': 'unique_list', 'additional_info': {
      //   'email_address' : {'key': 0, 'label': 'AGENT', 'type': 'single_text'},
      //   'contact_person' : {'key': 1, 'label': 'AGENT', 'type': 'single_text'},
      //   'additional_info' : {'key': 2, 'label': 'AGENT', 'type': 'single_text'},
      // }},
      // 'legal': {'key': 5, 'label': 'LEGALS', 'type': 'unique_list', 'additional_info': {
      //   'email_address' : {'key': 0, 'label': 'LEGALS', 'type': 'single_text'},
      //   'contact_person' : {'key': 1, 'label': 'LEGALS', 'type': 'single_text'},
      //   'additional_info' : {'key': 2, 'label': 'LEGALS', 'type': 'single_text'},
      // }},
      // 'sync_agency': {'key': 6, 'label': 'SYNC AGENCY', 'type': 'unique_list', 'additional_info': {
      //   'email_address' : {'key': 0, 'label': 'SYNC AGENCY', 'type': 'single_text'},
      //   'contact_person' : {'key': 1, 'label': 'SYNC AGENCY', 'type': 'single_text'},
      //   'additional_info' : {'key': 2, 'label': 'SYNC AGENCY', 'type': 'single_text'},
      // }},
      // 'management': {'key': 7, 'label': 'MANAGEMENT', 'type': 'unique_list', 'additional_info': {
      //   'email_address' : {'key': 0, 'label': 'MANAGEMENT', 'type': 'single_text'},
      //   'contact_person' : {'key': 1, 'label': 'MANAGEMENT', 'type': 'single_text'},
      //   'additional_info' : {'key': 2, 'label': 'MANAGEMENT', 'type': 'single_text'},
      // }},
      // 'general_contact' : {'key': 8, 'label': 'GENERAL CONTACT', 'type': 'single_text'}
      // }
}

export const avs = {
  'music_roles': {
    'name':'music_roles', 
    'values': [ 'Studio Personnel', 'Studio Producer', 'Surround Mixing Engineer', 'Surround Mixing Second Engineer']
  },
    'genres': {'name':'genres', 'values': [ 
      'acid jazz', 'acid rock', 'acid techno', 'acoustic blues', 
      'acoustic rock', 
      'afoxê', 
      'afrobeat', 
      'alternative country', 
      'alternative dance', 'alternative folk', 
      'alternative hip hop', 
      'alternative metal', 
      'alternative pop', 
      'alternative punk', 'alternative rock', 
      'ambient', 
      'ambient dub', 
      'ambient house', 
      'ambient techno', 
      'americana', 
      'anarcho-punk', 
      'aor', 
      'arena rock', 
      'art pop', 
      'art rock', 
      'atmospheric black metal', 
      'audiobook', 
      'avant-garde', 
      'avant-garde jazz', 
      'avant-garde metal', 
      'avant-garde pop', 
      'avant-prog', 
      'bachata', 'ballad', 
      'barbershop', 
      'baroque', 
      'bebop', 
      'bhangra', 
      'big band', 
      'big beat', 
      'black metal', 'blackened death metal', 
      'blackgaze', 
      'blue-eyed soul', 
      'bluegrass', 
      'blues', 
      'blues rock', 'bolero', 
      'bolero son', 
      'bongo flava', 
      'boogie rock', 
      'boogie-woogie', 
      'boom bap', 'bossa nova', 
      'bounce', 
      'breakbeat', 
      'breakbeat hardcore', 
      'breakcore', 
      'breaks', 
      'britpop', 
      'broken beat', 
      'brutal death metal', 
      'bubblegum pop', 
      'cajun', 
      'calypso', 
      'candombe', 
      'canterbury scene', 
      'cantopop', 
      'celtic', 
      'celtic punk', 
      'chamber pop', 
      'champeta', 
      'changüí', 
      'chanson', 
      'chicago blues', 
      'chillout', 
      'chiptune', 
      'christian rock', 
      'christmas music', 
      'chutney', 'city pop', 
      'classic blues', 
      'classic country', 
      'classic jazz', 
      'classic rock', 
      'classical', 
      'classical crossover', 
      'club', 
      'comedy', 
      'comedy rock', 
      'compas', 'conscious hip hop', 
      'contemporary christian', 
      'contemporary classical', 
      'contemporary folk', 
      'contemporary gospel', 
      'contemporary jazz', 
      'contemporary r&b', 
      'contra', 
      'cool jazz', 
      'country', 
      'country blues', 
      'country folk', 
      'country pop', 
      'country rock', 
      'coupé-décalé', 
      'cowpunk', 
      'crossover prog', 
      'crust punk', 
      'cumbia', 
      'cumbia villera', 
      'cyberpunk', 
      'd-beat', 
      'dance', 
      'dance-pop', 
      'dance-punk', 
      'dancehall', 
      'dark ambient', 
      'dark electro', 
      'dark folk', 
      'dark wave', 
      'death metal', 
      'death-doom metal', 
      'deathcore', 
      'deathgrind', 
      'deathrock', 
      'deep house', 
      'delta blues', 
      'descarga', 
      'desert rock', 
      'detroit techno', 
      'digital hardcore', 
      'disco', 
      'doo-wop', 
      'doom metal', 
      'downtempo', 
      'dream pop', 
      'drill', 
      'drill and bass', 
      'drone', 
      'drum and bass', 
      'dub', 
      'dub techno', 
      'dubstep', 
      'dungeon synth', 
      'east coast hip hop', 
      'ebm', 'edm', 'electric blues', 
      'electro', 
      'electro house', 
      'electro swing', 
      'electro-funk', 
      'electro-industrial', 
      'electroclash', 
      'electronic', 
      'electronic rock', 
      'electronica', 
      'electronicore', 
      'electropop', 
      'electropunk', 'emo', 'emocore', 
      'enka', 
      'ethereal', 
      'euro house', 
      'eurodance', 
      'europop', 
      'experimental', 
      'experimental rock', 
      'fado', 
      'filk', 
      'flamenco', 
      'folk', 
      'folk metal', 
      'folk pop', 
      'folk punk', 
      'folk rock', 
      'freak folk', 
      'free improvisation', 
      'free jazz', 
      'funk', 
      'funk carioca', 
      'funk metal', 
      'funk rock', 
      'funk soul', 
      'funky house', 
      'fusion', 
      'future garage', 
      'future jazz', 
      'futurepop', 
      'g-funk', 
      'gabber', 'gangsta rap', 'garage', 
      'garage house', 
      'garage punk', 
      'garage rock', 
      'glam', 
      'glam metal', 
      'glam rock', 
      'glitch', 
      'goa trance', 
      'goregrind', 
      'gospel', 
      'gothic', 
      'gothic metal', 
      'gothic rock', 
      'grebo', 
      'grime', 
      'grindcore', 
      'groove metal', 
      'group sounds', 
      'grunge', 
      'guaguancó', 
      'guajira', 
      'guaracha', 
      'happy hardcore', 
      'hard bop', 
      'hard house', 
      'hard rock', 
      'hard trance', 
      'hardcore hip hop', 
      'hardcore punk', 
      'hardcore techno', 
      'hardstyle', 
      'harsh noise', 
      'harsh noise wall', 
      'hauntology', 
      'heavy metal', 
      'heavy psych', 
      'heavy rock', 
      'hi-nrg', 
      'hip hop', 
      'hip house', 
      'honky tonk', 
      'horror punk', 
      'horrorcore', 
      'house', 'idm', 'illbient', 
      'indie', 
      'indie folk', 
      'indie pop', 
      'indie rock', 
      'indietronica', 
      'indorock', 
      'industrial', 
      'industrial metal', 
      'industrial musical', 
      'industrial rock', 
      'industrial techno', 
      'instrumental', 
      'instrumental jazz', 
      'instrumental rock', 
      'irish folk', 
      'italo-disco', 
      'j-pop', 
      'j-rock', 
      'jazz', 
      'jazz blues', 
      'jazz fusion', 
      'jazz rap', 
      'jazz rock', 
      'jazz-funk', 
      'joik', 
      'jungle', 
      'k-pop', 
      'kawaii metal', 
      'kayōkyoku', 
      'kizomba', 
      'klezmer', 
      'krautrock', 
      'latin', 
      'latin jazz', 
      'latin pop', 
      'latin rock', 
      'leftfield', 
      'line dance', 
      'lo-fi', 
      'lounge', 
      'lovers rock', 
      'madchester', 
      'mainstream rock', 
      'maloya', 
      'mambo', 
      'mandopop', 
      'martial industrial', 
      'maskanda', 
      'math rock', 
      'mathcore', 
      'medieval', 
      'melodic black metal', 
      'melodic death metal', 
      'melodic metalcore', 
      'melodic rock', 
      'melodic trance', 
      'mento', 
      'merengue', 
      'metal', 
      'metalcore', 
      'miami bass', 
      'microhouse', 
      'milonga', 
      'min yō', 
      'mincecore', 
      'minimal', 
      'minimal techno', 
      'minimal wave', 
      'modern blues', 
      'modern classical', 
      'modern country', 
      'motown', 
      'mpb', 
      'musical', 
      'neo soul', 
      'neo-progressive rock', 
      'neo-rockabilly', 
      'neo-traditional country', 
      'neofolk', 
      'nerdcore', 
      'new age', 
      'new jack swing', 
      'new romantic', 
      'new wave', 
      'nightcore', 
      'no wave', 
      'noise', 
      'noise pop', 
      'noise rock', 
      'noisecore', 
      'non-music', 
      'norteño', 
      'northern soul', 
      'nu jazz', 
      'nu metal', 
      'nueva canción', 
      'occult rock', 
      'oi', 
      'old school death metal', 
      'old-time', 
      'opera', 
      'orchestral', 
      'outlaw country', 
      'p-funk', 
      'pachanga', 
      'polka', 
      'pop', 
      'pop metal', 
      'pop punk', 
      'pop rap', 
      'pop rock', 
      'pop soul', 
      'pornogrind', 
      'post-bop', 
      'post-classical', 
      'post-grunge', 
      'post-hardcore', 
      'post-metal', 
      'post-punk', 
      'post-rock', 
      'power electronics', 
      'power metal', 
      'power pop', 
      'powerviolence', 
      'production music', 
      'progressive', 
      'progressive folk', 
      'progressive house', 
      'progressive metal', 
      'progressive rock', 
      'progressive trance', 
      'psy-trance', 
      'psychedelic', 
      'psychedelic folk', 
      'psychedelic pop', 
      'psychedelic rock', 
      'psychobilly', 
      'psytrance', 
      'punk', 
      'punk rock', 
      'queercore', 
      'r&b', 
      'ragga', 
      'ragga hip-hop', 
      'ragga jungle', 
      'ragtime', 
      'raï', 
      'ranchera', 
      'rap rock', 
      'rapcore', 
      'rave', 
      'red song', 
      'reggae', 
      'reggaeton', 
      'rhythmic noise', 
      'ritual ambient', 
      'rock', 
      'rock and roll', 
      'rockabilly', 
      'rocksteady', 
      'romantic classical', 
      'roots reggae', 
      'rumba', 
      'ryūkōka', 
      'salsa', 
      'samba', 
      'schlager', 
      'screamo', 
      'shibuya-kei', 
      'shoegaze', 
      'singer-songwriter', 
      'ska', 
      'ska punk', 
      'skacore', 
      'slow waltz', 
      'sludge metal', 
      'smooth jazz', 
      'smooth soul', 
      'soca', 
      'soft rock', 
      'son cubano', 
      'son montuno', 
      'soul', 
      'soul jazz', 
      'southern rock', 
      'southern soul', 
      'space rock', 
      'speed garage', 
      'speed metal', 
      'spoken word', 
      'steampunk', 
      'stoner metal', 
      'stoner rock', 
      'street punk', 
      'surf rock', 
      'swamp pop', 
      'swamp rock', 
      'swing', 
      'symphonic black metal', 
      'symphonic metal', 
      'symphonic prog', 
      'symphonic rock', 
      'symphony', 
      'synth-pop', 
      'synthwave', 
      'tango', 
      'tech house', 
      'technical death metal', 
      'techno', 
      'teen pop', 
      'thrash metal', 
      'thrashcore', 
      'timba', 
      'traditional country', 
      'trance', 
      'trap', 
      'trap edm', 
      'tribal ambient', 
      'tribal house', 
      'trip hop', 
      'turntablism', 
      'uk drill', 
      'uk funky', 
      'uk garage', 
      'underground hip hop', 
      'vallenato', 
      'vaporwave', 
      'viking metal', 
      'visual kei', 
      'vocal house', 
      'vocal jazz', 
      'vocal trance', 
      'waltz', 
      'west coast hip hop', 
      'west coast swing', 
      'western swing', 
      'yacht rock', 
      'yé-yé', 
      'zamrock', 
      'zeuhl', 
      'zouk', 
      'zydeco', 
      'add genre']
  },
  'non_music_roles': {
    'name':'non_music_roles', 
    'values': [ 'Manager', 'Producer']
  },
  'pr_agency': {
    'name':'pr_agency', 
    'values': []
  }
}


